In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import folium
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

In [11]:
df = pd.read_csv("raw_dataset_venda.csv" , sep =";", decimal =",", encoding = "UTF-8")
df

,NOME DO BAIRRO,AREA,HABITANTES,DOMICILIOS,RENDA MEDIA,PRECO VENDA,LATITUDE,LONGITUDE,CICLOVIAS (KM),ESTACOES TUBO,UNIDADES DE SAUDE PUBLICAS,CENTROS MÉDICOS PARTICULARES,LAZER PÚBLICO,LAZER PRIVADO,EDUCACAO PUBLICA,EDUCACAO PRIVADA,CRIMES CONTRA A VIDA,CRIMES CONTRA O PATRIMONIO,COMERCIO,INDUSTRIA
0,BOM RETIRO,1.94,6760,1780,2132,5350,-25.409228,-49.276760,0.0,1,0,1,1,0,1,11,0,28,382,29
1,CASCATINHA,2.57,2473,586,2198,6062,-25.413470,-49.311648,2.1,0,1,0,0,0,0,0,0,5,78,3
2,RIVIERA,2.36,244,62,423,4810,-25.436042,-49.380925,0.0,0,0,0,0,0,0,0,0,0,0,0
3,LAMENHA PEQUENA,3.40,841,188,665,4093,-25.364845,-49.337269,0.0,0,0,0,0,0,0,0,2,0,17,3
4,JARDIM SOCIAL,1.89,7302,1674,4606,6905,-25.417852,-49.234731,0.0,1,1,1,1,0,2,5,5,0,52,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,BOQUEIRÃO,14.80,82194,19750,1413,4352,-25.501348,-49.236188,6.8,7,5,0,0,0,24,39,581,2294,4811,994
71,CAJURU,11.55,107741,14301,793,4564,-25.458630,-49.206812,0.2,8,7,0,1,0,27,31,700,2451,1884,271
72,CIDADE INDUSTRIAL,43.38,188953,43494,639,5324,-25.506966,-49.338198,13.9,4,18,1,3,1,81,29,745,3521,3157,912
73,SITIO CERCADO,11.12,122881,27914,934,3191,-25.543151,-49.267727,5.6,5,11,0,1,0,48,19,762,3326,2865,330
74,CENTRO,3.30,39148,14576,2221,7326,-25.432527,-49.269647,2.8,18,1,3,6,9,12,64,2511,6497,8712,265

In [12]:
df = df.drop('NOME DO BAIRRO', axis = 1)
ss = StandardScaler()
X = ss.fit_transform(X)
print(X)

NameError: name 'X' is not defined